# Generated by Django 4.0.1 on 2022-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
